import { GEMINI_API_KEY, GEMINI_API_URL, GEMINI_MODEL } from '../config/gemini';

const geminiService = {
  async generateContent(imageData) {
    try {
      console.log('Starting Gemini API request...');
      console.log('API Configuration:', {
        url: `${GEMINI_API_URL}/models/gemini-pro-vision:generateContent`,
        apiKeyLength: GEMINI_API_KEY.length,
        startsWithAIza: GEMINI_API_KEY.startsWith('AIza')
      });

      try {
        const response = await fetch(`${GEMINI_API_URL}/models/gemini-pro-vision:generateContent`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${GEMINI_API_KEY}`,
            'X-Goog-Api-Key': GEMINI_API_KEY,
            'Accept': 'application/json',
            'User-Agent': 'Visionverse/1.0',
            'X-Goog-Api-Key-Version': '1.0'
          },
          body: JSON.stringify({
            contents: [
              {
                inlineData: {
                  mimeType: 'image/jpeg',
                  data: imageData
                }
              }
            ],
            generationConfig: {
              temperature: 0.7,
              topP: 0.8,
              topK: 40,
              maxOutputTokens: 2048,
              candidateCount: 1
            }
          })
        });

        if (!response.ok) {
          const error = await response.json();
          console.error('Gemini API Error Details:', {
            status: response.status,
            statusText: response.statusText,
            error: error,
            headers: Object.fromEntries(response.headers.entries())
          });

          const errorMessage = `Gemini API Error (${response.status}): ${error.message || response.statusText}`;
          console.error(errorMessage);
          throw new Error(errorMessage);
        }
      } catch (error) {
        console.error('Gemini API Request Error:', {
          message: error.message,
          stack: error.stack,
          name: error.name
        });

        if (error.response) {
          console.error('API Response Details:', {
            status: error.response.status,
            statusText: error.response.statusText,
            data: error.response.data
          });
        }

        throw error;
      }

      const data = await response.json();
      console.log('Gemini API Response:', {
        status: response.status,
        candidates: data.candidates?.length,
        response: data
      });

      if (!data.candidates || data.candidates.length === 0) {
        throw new Error('No content generated by Gemini API');
      }

      return data.candidates[0].content.parts[0].text.trim();
    } catch (error) {
      console.error('Error in generateContent:', error);
      throw error;
    }
  }
};

export default geminiService;
